server:
  port: 8001
spring:
  application:
    name: admin-server

eureka:
  client:
    #从服务中心获取其他服务的地址
    fetchRegistry: true
    serviceUrl: #单机版
      defaultZone: http://eureka8761.com:8761/eureka
      #注册服务到eureka集群
      #defaultZone: http://eureka8761.com:8761/eureka,http://eureka8762.com:8762/eureka,http://eureka8763.com:8763/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port} #微服务信息提示为服务名：端口,可自定义
    prefer-ip-address: true     #访问路径可以显示IP地址

#OpenFeign 默认支持Ribbon
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是连接后从服务器读取到可用资源所用的时间（默认是1秒）
  ConnectTimeout: 5000

#某个类的日志级别
logging:
  level:
    #feign 日志以什么级别监控哪个接口
    com.module.admin.service.UserFeignService: debug

#微服务信息
info:
  app.name: admin-server
  company.name: www.jty.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@