server:
  port: 8761

eureka:
  instance:
    hostname: eureka8761.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8761.com:8761/eureka