server:
  port: 9527

spring:
  application:
    name: getway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启服务发现，可以服务作为转发目标，为 false 时使用地址转发
      routes:
        # 认证中心
        - id: admin-server
          uri: lb://admin-server #转发后的微服务名 以lb开头
#          uri: http://localhost:8001 #转发后的地址
          predicates:
            #- Path=/admin/**   #请求断言，以路径方式以author开头的请求路径转发到uri，官方提供多种断言方式，可结合使用
            - Path=/**   #所有请求
          filters:
            - StripPrefix=1 #过滤器，对请求进行一系列操作，如请求，权限认证，鉴权，监控，限流，转发等,StripPrefix 去掉一层请求（去掉admin）
         #最终形式，如https://localhost:9527/admin/get/user/6 =>https://localhost:8001/admin/get/user/6
eureka:
  client:
    serviceUrl:
      #单机
      defaultZone: http://eureka8761.com:8761/eureka
      #注册服务到eureka集群
      #defaultZone: http://eureka8761.com:8761/eureka,http://eureka8762.com:8762/eureka,http://eureka8763.com:8763/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址

#微服务信息
info:
  app.name: getway-server
  company.name: www.jty.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@