server:
  port: 9101
spring:
  application:
    name: order-server
  #配置nacos服务注册中心地址、配置中心地址
  cloud:
    nacos:
      discovery:
        #服务注册中心
        server-addr: 127.0.0.1:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_db?useUnicode=true&characterEncoding=utf8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

    initialSize: 2  #最小连接数
    minIdle: 1 #最小空闲
    maxActive: 2o #最大连接数
    maxWait: 60000 #最长等待时间
    timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: "select 'x'"
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
mybatis:
  ### xml存放路径
  mapper-locations: classpath:mapper/*Mapper.xml

#OpenFeign 默认支持Ribbon
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是连接后从服务器读取到可用资源所用的时间（默认是1秒）
  ConnectTimeout: 5000

#mybatis 日志
logging:
  level:
    com.jty.*.dao: debug

#开启所有端点允许HTTP查看
management:
  endpoints:
    web:
      exposure:
        include: "*"

#namespace:DEV
#Group: DEV
#Data ID: user-server-dev.yaml