server:
  port: 8762

eureka:
  instance:
    hostname: eureka8762.com
  client:
    registerWithEureka: false #注册自己
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka8761.com:8761/eureka,http://eureka8763.com:8763/eureka