server:
  port: 8762  #端口

eureka:
  instance:
    #hostname: localhost
    hostname: eureka8762.com  #服务名
  client:
    registerWithEureka: false #注册自己
    fetchRegistry: false
    serviceUrl:
      #单机
      #defaultZone:http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群
      defaultZone: http://eureka8762.com:8762/eureka,http://eureka8761.com:8761/eureka